/** Generated by pnpm native3d:identity:generate; checked by schema:check.
 * Conservative first-party value-import closure, including this descriptor itself.
 * Browser-safe data; installed release rewrites only literal .ts URLs to .js. */
export const native3DAppearanceModules: readonly {
  readonly name: string;
  readonly url: URL;
}[] = Object.freeze([
  {
    name: "catalogs/ecommerce-motion/capabilities.json",
    url: new URL(
      "../../../../catalogs/ecommerce-motion/capabilities.json",
      import.meta.url,
    ),
  },
  {
    name: "catalogs/ecommerce-motion/source/v1.0/library_data.json",
    url: new URL(
      "../../../../catalogs/ecommerce-motion/source/v1.0/library_data.json",
      import.meta.url,
    ),
  },
  {
    name: "renderer-core/src/alpha-coverage.ts",
    url: new URL("../alpha-coverage.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/browser-checksum.ts",
    url: new URL("../browser-checksum.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/brush-path.ts",
    url: new URL("../brush-path.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/camera-sampling.ts",
    url: new URL("../camera-sampling.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/cinematic-scene.ts",
    url: new URL("../cinematic-scene.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/commerce-composition.ts",
    url: new URL("../commerce-composition.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/commerce-effect-motion.ts",
    url: new URL("../commerce-effect-motion.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/commerce-exposure.ts",
    url: new URL("../commerce-exposure.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/commerce-floating.ts",
    url: new URL("../commerce-floating.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/commerce-geometry.ts",
    url: new URL("../commerce-geometry.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/commerce-motion.ts",
    url: new URL("../commerce-motion.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/commerce-path.ts",
    url: new URL("../commerce-path.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/commerce-scene.ts",
    url: new URL("../commerce-scene.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/commerce-text.ts",
    url: new URL("../commerce-text.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/component-annotations.ts",
    url: new URL("../component-annotations.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/component-capabilities.ts",
    url: new URL("../component-capabilities.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/component-pin.ts",
    url: new URL("../component-pin.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/component-relationships.ts",
    url: new URL("../component-relationships.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/component-state.ts",
    url: new URL("../component-state.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/component-text-fit.ts",
    url: new URL("../component-text-fit.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/component-travel.ts",
    url: new URL("../component-travel.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/component-values.ts",
    url: new URL("../component-values.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/component-visibility.ts",
    url: new URL("../component-visibility.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/adapters/appearance-providers.ts",
    url: new URL(
      "../composition/adapters/appearance-providers.ts",
      import.meta.url,
    ),
  },
  {
    name: "renderer-core/src/composition/adapters/appearance.ts",
    url: new URL("../composition/adapters/appearance.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/adapters/cinematic-coverage.ts",
    url: new URL(
      "../composition/adapters/cinematic-coverage.ts",
      import.meta.url,
    ),
  },
  {
    name: "renderer-core/src/composition/adapters/commerce-path.ts",
    url: new URL("../composition/adapters/commerce-path.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/adapters/commerce-providers.ts",
    url: new URL(
      "../composition/adapters/commerce-providers.ts",
      import.meta.url,
    ),
  },
  {
    name: "renderer-core/src/composition/adapters/family-state.ts",
    url: new URL("../composition/adapters/family-state.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/adapters/motion-path.ts",
    url: new URL("../composition/adapters/motion-path.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/adapters/numeric-typography.ts",
    url: new URL(
      "../composition/adapters/numeric-typography.ts",
      import.meta.url,
    ),
  },
  {
    name: "renderer-core/src/composition/adapters/prepared.ts",
    url: new URL("../composition/adapters/prepared.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/adapters/provider-bounds.ts",
    url: new URL("../composition/adapters/provider-bounds.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/adapters/story-coverage.ts",
    url: new URL("../composition/adapters/story-coverage.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/adapters/story-path.ts",
    url: new URL("../composition/adapters/story-path.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/adapters/story-providers.ts",
    url: new URL("../composition/adapters/story-providers.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/evaluate/adaptive.ts",
    url: new URL("../composition/evaluate/adaptive.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/evaluate/camera.ts",
    url: new URL("../composition/evaluate/camera.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/evaluate/compile.ts",
    url: new URL("../composition/evaluate/compile.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/evaluate/constraints.ts",
    url: new URL("../composition/evaluate/constraints.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/evaluate/depth-image.ts",
    url: new URL("../composition/evaluate/depth-image.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/evaluate/effects.ts",
    url: new URL("../composition/evaluate/effects.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/evaluate/evaluate.ts",
    url: new URL("../composition/evaluate/evaluate.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/evaluate/exposure.ts",
    url: new URL("../composition/evaluate/exposure.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/evaluate/expression-keys.ts",
    url: new URL("../composition/evaluate/expression-keys.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/evaluate/expression-math.ts",
    url: new URL("../composition/evaluate/expression-math.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/evaluate/geometry.ts",
    url: new URL("../composition/evaluate/geometry.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/evaluate/lighting.ts",
    url: new URL("../composition/evaluate/lighting.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/evaluate/media-clock.ts",
    url: new URL("../composition/evaluate/media-clock.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/evaluate/media.ts",
    url: new URL("../composition/evaluate/media.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/evaluate/properties.ts",
    url: new URL("../composition/evaluate/properties.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/evaluate/sample-clock.ts",
    url: new URL("../composition/evaluate/sample-clock.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/evaluate/sample.ts",
    url: new URL("../composition/evaluate/sample.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/evaluate/spatial-geometry.ts",
    url: new URL(
      "../composition/evaluate/spatial-geometry.ts",
      import.meta.url,
    ),
  },
  {
    name: "renderer-core/src/composition/evaluate/spatial-orient.ts",
    url: new URL("../composition/evaluate/spatial-orient.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/evaluate/spatial-scope.ts",
    url: new URL("../composition/evaluate/spatial-scope.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/evaluate/spatial-state.ts",
    url: new URL("../composition/evaluate/spatial-state.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/evaluate/time-controls.ts",
    url: new URL("../composition/evaluate/time-controls.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/evaluate/version.ts",
    url: new URL("../composition/evaluate/version.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/mesh/bounds.ts",
    url: new URL("../composition/mesh/bounds.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/mesh/contours.ts",
    url: new URL("../composition/mesh/contours.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/mesh/diagnostics.ts",
    url: new URL("../composition/mesh/diagnostics.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/mesh/frame.ts",
    url: new URL("../composition/mesh/frame.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/mesh/geometry.ts",
    url: new URL("../composition/mesh/geometry.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/mesh/quality.ts",
    url: new URL("../composition/mesh/quality.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/mesh/raster.ts",
    url: new URL("../composition/mesh/raster.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/mesh/topology.ts",
    url: new URL("../composition/mesh/topology.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/backend.ts",
    url: new URL("../composition/render/backend.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/batches.ts",
    url: new URL("../composition/render/batches.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/canvas-color.ts",
    url: new URL("../composition/render/canvas-color.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/canvas-linear.ts",
    url: new URL("../composition/render/canvas-linear.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/canvas2d.ts",
    url: new URL("../composition/render/canvas2d.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/cinematic-reveal.ts",
    url: new URL("../composition/render/cinematic-reveal.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/color-effects.ts",
    url: new URL("../composition/render/color-effects.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/draw-shapes.ts",
    url: new URL("../composition/render/draw-shapes.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/effect-plugins.ts",
    url: new URL("../composition/render/effect-plugins.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/effect-window.ts",
    url: new URL("../composition/render/effect-window.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/effects.ts",
    url: new URL("../composition/render/effects.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/exposure.ts",
    url: new URL("../composition/render/exposure.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/flat-lighting.ts",
    url: new URL("../composition/render/flat-lighting.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/gradient-controls.ts",
    url: new URL("../composition/render/gradient-controls.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/graph.ts",
    url: new URL("../composition/render/graph.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/graphs.ts",
    url: new URL("../composition/render/graphs.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/linear-color.ts",
    url: new URL("../composition/render/linear-color.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/map-effects.ts",
    url: new URL("../composition/render/map-effects.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/media-resources.ts",
    url: new URL("../composition/render/media-resources.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/mesh-effects.ts",
    url: new URL("../composition/render/mesh-effects.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/native-text-bounds.ts",
    url: new URL(
      "../composition/render/native-text-bounds.ts",
      import.meta.url,
    ),
  },
  {
    name: "renderer-core/src/composition/render/noise-effects.ts",
    url: new URL("../composition/render/noise-effects.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/prefix-dependencies.ts",
    url: new URL(
      "../composition/render/prefix-dependencies.ts",
      import.meta.url,
    ),
  },
  {
    name: "renderer-core/src/composition/render/prefix.ts",
    url: new URL("../composition/render/prefix.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/projected-mask.ts",
    url: new URL("../composition/render/projected-mask.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/projective-placement.ts",
    url: new URL(
      "../composition/render/projective-placement.ts",
      import.meta.url,
    ),
  },
  {
    name: "renderer-core/src/composition/render/providers.ts",
    url: new URL("../composition/render/providers.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/radial-distortion.ts",
    url: new URL("../composition/render/radial-distortion.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/renderer.ts",
    url: new URL("../composition/render/renderer.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/required-coverage.ts",
    url: new URL("../composition/render/required-coverage.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/root-cache.ts",
    url: new URL("../composition/render/root-cache.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/sampled-blur.ts",
    url: new URL("../composition/render/sampled-blur.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/shadow-effects.ts",
    url: new URL("../composition/render/shadow-effects.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/source-cache.ts",
    url: new URL("../composition/render/source-cache.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/source-preparation.ts",
    url: new URL(
      "../composition/render/source-preparation.ts",
      import.meta.url,
    ),
  },
  {
    name: "renderer-core/src/composition/render/spatial-capabilities.ts",
    url: new URL(
      "../composition/render/spatial-capabilities.ts",
      import.meta.url,
    ),
  },
  {
    name: "renderer-core/src/composition/render/spatial-order.ts",
    url: new URL("../composition/render/spatial-order.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/statistics.ts",
    url: new URL("../composition/render/statistics.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/stylize-effects.ts",
    url: new URL("../composition/render/stylize-effects.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/surface-cache.ts",
    url: new URL("../composition/render/surface-cache.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/text-bounds.ts",
    url: new URL("../composition/render/text-bounds.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/text-clock.ts",
    url: new URL("../composition/render/text-clock.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/text-frames.ts",
    url: new URL("../composition/render/text-frames.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/text.ts",
    url: new URL("../composition/render/text.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/transition-effects.ts",
    url: new URL(
      "../composition/render/transition-effects.ts",
      import.meta.url,
    ),
  },
  {
    name: "renderer-core/src/composition/render/version.ts",
    url: new URL("../composition/render/version.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/warp-effects.ts",
    url: new URL("../composition/render/warp-effects.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/webgl-blend.ts",
    url: new URL("../composition/render/webgl-blend.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/webgl-blur-kernel.ts",
    url: new URL("../composition/render/webgl-blur-kernel.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/webgl-blur-padding.ts",
    url: new URL(
      "../composition/render/webgl-blur-padding.ts",
      import.meta.url,
    ),
  },
  {
    name: "renderer-core/src/composition/render/webgl-blur-rescale.ts",
    url: new URL(
      "../composition/render/webgl-blur-rescale.ts",
      import.meta.url,
    ),
  },
  {
    name: "renderer-core/src/composition/render/webgl-bounds.ts",
    url: new URL("../composition/render/webgl-bounds.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/webgl-box-blur.ts",
    url: new URL("../composition/render/webgl-box-blur.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/webgl-damage.ts",
    url: new URL("../composition/render/webgl-damage.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/webgl-depth-image.ts",
    url: new URL("../composition/render/webgl-depth-image.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/webgl-depth-text.ts",
    url: new URL("../composition/render/webgl-depth-text.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/webgl-device.ts",
    url: new URL("../composition/render/webgl-device.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/webgl-disjoint-paints.ts",
    url: new URL(
      "../composition/render/webgl-disjoint-paints.ts",
      import.meta.url,
    ),
  },
  {
    name: "renderer-core/src/composition/render/webgl-effects.ts",
    url: new URL("../composition/render/webgl-effects.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/webgl-exposure.ts",
    url: new URL("../composition/render/webgl-exposure.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/webgl-float-sum.ts",
    url: new URL("../composition/render/webgl-float-sum.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/webgl-images.ts",
    url: new URL("../composition/render/webgl-images.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/webgl-isolates.ts",
    url: new URL("../composition/render/webgl-isolates.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/webgl-mesh.ts",
    url: new URL("../composition/render/webgl-mesh.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/webgl-native-depth.ts",
    url: new URL(
      "../composition/render/webgl-native-depth.ts",
      import.meta.url,
    ),
  },
  {
    name: "renderer-core/src/composition/render/webgl-native-state.ts",
    url: new URL(
      "../composition/render/webgl-native-state.ts",
      import.meta.url,
    ),
  },
  {
    name: "renderer-core/src/composition/render/webgl-paint.ts",
    url: new URL("../composition/render/webgl-paint.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/webgl-path-bounds.ts",
    url: new URL("../composition/render/webgl-path-bounds.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/webgl-png-images.ts",
    url: new URL("../composition/render/webgl-png-images.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/webgl-projective.ts",
    url: new URL("../composition/render/webgl-projective.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/webgl-readback.ts",
    url: new URL("../composition/render/webgl-readback.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/webgl-rgba.ts",
    url: new URL("../composition/render/webgl-rgba.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/webgl-vector-paints.ts",
    url: new URL(
      "../composition/render/webgl-vector-paints.ts",
      import.meta.url,
    ),
  },
  {
    name: "renderer-core/src/composition/render/webgl-vector-regions.ts",
    url: new URL(
      "../composition/render/webgl-vector-regions.ts",
      import.meta.url,
    ),
  },
  {
    name: "renderer-core/src/composition/render/webgl-vectors.ts",
    url: new URL("../composition/render/webgl-vectors.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/webgl-visual-key.ts",
    url: new URL("../composition/render/webgl-visual-key.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/render/webgl2.ts",
    url: new URL("../composition/render/webgl2.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/shapes/budget.ts",
    url: new URL("../composition/shapes/budget.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/shapes/compile.ts",
    url: new URL("../composition/shapes/compile.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/shapes/deform.ts",
    url: new URL("../composition/shapes/deform.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/shapes/geometry.ts",
    url: new URL("../composition/shapes/geometry.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/shapes/nib.ts",
    url: new URL("../composition/shapes/nib.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/shapes/path.ts",
    url: new URL("../composition/shapes/path.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/shapes/polygons.ts",
    url: new URL("../composition/shapes/polygons.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/shapes/primitives.ts",
    url: new URL("../composition/shapes/primitives.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/shapes/repeater.ts",
    url: new URL("../composition/shapes/repeater.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/shapes/sample.ts",
    url: new URL("../composition/shapes/sample.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/shapes/trim.ts",
    url: new URL("../composition/shapes/trim.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/composition/typography-source-frame.ts",
    url: new URL("../composition/typography-source-frame.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/connector-points.ts",
    url: new URL("../connector-points.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/curve.ts",
    url: new URL("../curve.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/depth-reframe.ts",
    url: new URL("../depth-reframe.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/font-cmap.ts",
    url: new URL("../font-cmap.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/font-copy.ts",
    url: new URL("../font-copy.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/font-identity.ts",
    url: new URL("../font-identity.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/font-metrics.ts",
    url: new URL("../font-metrics.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/font-sfnt.ts",
    url: new URL("../font-sfnt.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/frame-tracks.ts",
    url: new URL("../frame-tracks.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/ink-path.ts",
    url: new URL("../ink-path.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/managed-memory-context.ts",
    url: new URL("../managed-memory-context.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/managed-metadata-hash.ts",
    url: new URL("../managed-metadata-hash.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/managed-metadata.ts",
    url: new URL("../managed-metadata.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/managed-resources.ts",
    url: new URL("../managed-resources.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/mechanism/canonical.ts",
    url: new URL("../mechanism/canonical.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/mechanism/evaluate.ts",
    url: new URL("../mechanism/evaluate.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/mechanism/matrix.ts",
    url: new URL("../mechanism/matrix.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/mechanism/projection.ts",
    url: new URL("../mechanism/projection.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/mechanism/types.ts",
    url: new URL("../mechanism/types.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/motion-appearance.ts",
    url: new URL("../motion-appearance.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/motion-craft.ts",
    url: new URL("../motion-craft.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/motion-easing.ts",
    url: new URL("../motion-easing.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/motion-sampling.ts",
    url: new URL("../motion-sampling.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/motion-text.ts",
    url: new URL("../motion-text.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/native3d/appearance-modules.ts",
    url: new URL("./appearance-modules.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/native3d/bindings.ts",
    url: new URL("./bindings.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/native3d/browser.ts",
    url: new URL("./browser.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/native3d/evaluate.ts",
    url: new URL("./evaluate.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/native3d/observations.ts",
    url: new URL("./observations.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/native3d/prepare.ts",
    url: new URL("./prepare.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/native3d/resolve.ts",
    url: new URL("./resolve.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/native3d/three-graphics.ts",
    url: new URL("./three-graphics.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/native3d/three-materials.ts",
    url: new URL("./three-materials.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/native3d/three-observation.ts",
    url: new URL("./three-observation.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/native3d/three-textures.ts",
    url: new URL("./three-textures.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/native3d/three-world.ts",
    url: new URL("./three-world.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/native3d/visibility.ts",
    url: new URL("./visibility.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/node-transform.ts",
    url: new URL("../node-transform.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/passage-diagnostics.ts",
    url: new URL("../passage-diagnostics.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/pixel-effects.ts",
    url: new URL("../pixel-effects.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/pixel-generators.ts",
    url: new URL("../pixel-generators.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/prepared-fonts.ts",
    url: new URL("../prepared-fonts.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/prepared-path-renderer.ts",
    url: new URL("../prepared-path-renderer.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/prepared-rect-renderer.ts",
    url: new URL("../prepared-rect-renderer.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/prepared-scene.ts",
    url: new URL("../prepared-scene.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/product-float.ts",
    url: new URL("../product-float.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/product-layer.ts",
    url: new URL("../product-layer.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/reveal-validation.ts",
    url: new URL("../reveal-validation.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/safe-zone-geometry.ts",
    url: new URL("../safe-zone-geometry.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/scene.ts",
    url: new URL("../scene.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/shaped-text.ts",
    url: new URL("../shaped-text.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/story-camera.ts",
    url: new URL("../story-camera.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/story-choreography.ts",
    url: new URL("../story-choreography.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/story-event-index.ts",
    url: new URL("../story-event-index.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/story-flows.ts",
    url: new URL("../story-flows.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/story-generic.ts",
    url: new URL("../story-generic.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/story-geometry.ts",
    url: new URL("../story-geometry.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/story-motion-presets.ts",
    url: new URL("../story-motion-presets.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/story-props.ts",
    url: new URL("../story-props.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/story-safe-zones.ts",
    url: new URL("../story-safe-zones.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/story-scene.ts",
    url: new URL("../story-scene.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/story-text-layout.ts",
    url: new URL("../story-text-layout.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/story-text.ts",
    url: new URL("../story-text.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/text-container-layout.ts",
    url: new URL("../text-container-layout.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/text-container.ts",
    url: new URL("../text-container.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/text-layout.ts",
    url: new URL("../text-layout.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/typography-animation.ts",
    url: new URL("../typography-animation.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/typography-axes.ts",
    url: new URL("../typography-axes.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/typography-decorations.ts",
    url: new URL("../typography-decorations.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/typography-events.ts",
    url: new URL("../typography-events.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/typography-renderer.ts",
    url: new URL("../typography-renderer.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/typography-style.ts",
    url: new URL("../typography-style.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/typography-text-values.ts",
    url: new URL("../typography-text-values.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/typography-transition.ts",
    url: new URL("../typography-transition.ts", import.meta.url),
  },
  {
    name: "renderer-core/src/typography-visibility.ts",
    url: new URL("../typography-visibility.ts", import.meta.url),
  },
  {
    name: "scene-contract/src/character-actions.ts",
    url: new URL(
      "../../../scene-contract/src/character-actions.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/cinematic.ts",
    url: new URL("../../../scene-contract/src/cinematic.ts", import.meta.url),
  },
  {
    name: "scene-contract/src/commerce-catalog.ts",
    url: new URL(
      "../../../scene-contract/src/commerce-catalog.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/commerce-components.ts",
    url: new URL(
      "../../../scene-contract/src/commerce-components.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/commerce-effects.ts",
    url: new URL(
      "../../../scene-contract/src/commerce-effects.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/commerce-library.ts",
    url: new URL(
      "../../../scene-contract/src/commerce-library.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/commerce-spatial-demos.ts",
    url: new URL(
      "../../../scene-contract/src/commerce-spatial-demos.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/commerce-spatial.ts",
    url: new URL(
      "../../../scene-contract/src/commerce-spatial.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/commerce.ts",
    url: new URL("../../../scene-contract/src/commerce.ts", import.meta.url),
  },
  {
    name: "scene-contract/src/component-data.ts",
    url: new URL(
      "../../../scene-contract/src/component-data.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/components.ts",
    url: new URL("../../../scene-contract/src/components.ts", import.meta.url),
  },
  {
    name: "scene-contract/src/composition/audio-clock.ts",
    url: new URL(
      "../../../scene-contract/src/composition/audio-clock.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/audio-pcm.ts",
    url: new URL(
      "../../../scene-contract/src/composition/audio-pcm.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/audio.ts",
    url: new URL(
      "../../../scene-contract/src/composition/audio.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/behaviours.ts",
    url: new URL(
      "../../../scene-contract/src/composition/behaviours.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/blur-effects.ts",
    url: new URL(
      "../../../scene-contract/src/composition/blur-effects.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/camera-dependencies.ts",
    url: new URL(
      "../../../scene-contract/src/composition/camera-dependencies.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/color-effects.ts",
    url: new URL(
      "../../../scene-contract/src/composition/color-effects.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/composition.ts",
    url: new URL(
      "../../../scene-contract/src/composition/composition.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/curves.ts",
    url: new URL(
      "../../../scene-contract/src/composition/curves.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/dependencies.ts",
    url: new URL(
      "../../../scene-contract/src/composition/dependencies.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/depth-image.ts",
    url: new URL(
      "../../../scene-contract/src/composition/depth-image.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/diagnostics.ts",
    url: new URL(
      "../../../scene-contract/src/composition/diagnostics.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/effect-curves.ts",
    url: new URL(
      "../../../scene-contract/src/composition/effect-curves.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/effect-definition.ts",
    url: new URL(
      "../../../scene-contract/src/composition/effect-definition.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/effect-points.ts",
    url: new URL(
      "../../../scene-contract/src/composition/effect-points.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/effects.ts",
    url: new URL(
      "../../../scene-contract/src/composition/effects.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/expression-ast.ts",
    url: new URL(
      "../../../scene-contract/src/composition/expression-ast.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/expression-check.ts",
    url: new URL(
      "../../../scene-contract/src/composition/expression-check.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/expressions.ts",
    url: new URL(
      "../../../scene-contract/src/composition/expressions.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/index.ts",
    url: new URL(
      "../../../scene-contract/src/composition/index.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/keys.ts",
    url: new URL(
      "../../../scene-contract/src/composition/keys.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/layers.ts",
    url: new URL(
      "../../../scene-contract/src/composition/layers.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/map-effects.ts",
    url: new URL(
      "../../../scene-contract/src/composition/map-effects.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/media.ts",
    url: new URL(
      "../../../scene-contract/src/composition/media.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/mesh-effects.ts",
    url: new URL(
      "../../../scene-contract/src/composition/mesh-effects.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/motion.ts",
    url: new URL(
      "../../../scene-contract/src/composition/motion.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/native3d-edit.ts",
    url: new URL(
      "../../../scene-contract/src/composition/native3d-edit.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/native3d.ts",
    url: new URL(
      "../../../scene-contract/src/composition/native3d.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/noise-effects.ts",
    url: new URL(
      "../../../scene-contract/src/composition/noise-effects.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/primitives.ts",
    url: new URL(
      "../../../scene-contract/src/composition/primitives.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/property-path.ts",
    url: new URL(
      "../../../scene-contract/src/composition/property-path.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/radial-distortion.ts",
    url: new URL(
      "../../../scene-contract/src/composition/radial-distortion.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/resolve.ts",
    url: new URL(
      "../../../scene-contract/src/composition/resolve.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/shadow-effects.ts",
    url: new URL(
      "../../../scene-contract/src/composition/shadow-effects.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/shape-properties.ts",
    url: new URL(
      "../../../scene-contract/src/composition/shape-properties.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/shapes.ts",
    url: new URL(
      "../../../scene-contract/src/composition/shapes.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/stylize-effects.ts",
    url: new URL(
      "../../../scene-contract/src/composition/stylize-effects.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/text-axes.ts",
    url: new URL(
      "../../../scene-contract/src/composition/text-axes.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/transition-effects.ts",
    url: new URL(
      "../../../scene-contract/src/composition/transition-effects.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/typography.ts",
    url: new URL(
      "../../../scene-contract/src/composition/typography.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/validate-media.ts",
    url: new URL(
      "../../../scene-contract/src/composition/validate-media.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/validate-native3d.ts",
    url: new URL(
      "../../../scene-contract/src/composition/validate-native3d.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/validate-spatial.ts",
    url: new URL(
      "../../../scene-contract/src/composition/validate-spatial.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/validate.ts",
    url: new URL(
      "../../../scene-contract/src/composition/validate.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/composition/warp-effects.ts",
    url: new URL(
      "../../../scene-contract/src/composition/warp-effects.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/contracts.ts",
    url: new URL("../../../scene-contract/src/contracts.ts", import.meta.url),
  },
  {
    name: "scene-contract/src/corpus.ts",
    url: new URL("../../../scene-contract/src/corpus.ts", import.meta.url),
  },
  {
    name: "scene-contract/src/depth-worker.ts",
    url: new URL(
      "../../../scene-contract/src/depth-worker.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/easing-sampler.ts",
    url: new URL(
      "../../../scene-contract/src/easing-sampler.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/errors.ts",
    url: new URL("../../../scene-contract/src/errors.ts", import.meta.url),
  },
  {
    name: "scene-contract/src/failure-diagnostics.ts",
    url: new URL(
      "../../../scene-contract/src/failure-diagnostics.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/index.ts",
    url: new URL("../../../scene-contract/src/index.ts", import.meta.url),
  },
  {
    name: "scene-contract/src/intent-presets.ts",
    url: new URL(
      "../../../scene-contract/src/intent-presets.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/mechanism/episode.ts",
    url: new URL(
      "../../../scene-contract/src/mechanism/episode.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/mechanism/frame.ts",
    url: new URL(
      "../../../scene-contract/src/mechanism/frame.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/mechanism/geometry.ts",
    url: new URL(
      "../../../scene-contract/src/mechanism/geometry.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/mechanism/index.ts",
    url: new URL(
      "../../../scene-contract/src/mechanism/index.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/mechanism/primitives.ts",
    url: new URL(
      "../../../scene-contract/src/mechanism/primitives.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/mechanism/scene.ts",
    url: new URL(
      "../../../scene-contract/src/mechanism/scene.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/mechanism/sidecar.ts",
    url: new URL(
      "../../../scene-contract/src/mechanism/sidecar.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/motion-craft-validation.ts",
    url: new URL(
      "../../../scene-contract/src/motion-craft-validation.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/motion-craft.ts",
    url: new URL(
      "../../../scene-contract/src/motion-craft.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/motion-easing.ts",
    url: new URL(
      "../../../scene-contract/src/motion-easing.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/narration-timing.ts",
    url: new URL(
      "../../../scene-contract/src/narration-timing.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/native3d/appearance.ts",
    url: new URL(
      "../../../scene-contract/src/native3d/appearance.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/native3d/frame.ts",
    url: new URL(
      "../../../scene-contract/src/native3d/frame.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/native3d/geometry.ts",
    url: new URL(
      "../../../scene-contract/src/native3d/geometry.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/native3d/index.ts",
    url: new URL(
      "../../../scene-contract/src/native3d/index.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/native3d/observation.ts",
    url: new URL(
      "../../../scene-contract/src/native3d/observation.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/native3d/scene.ts",
    url: new URL(
      "../../../scene-contract/src/native3d/scene.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/output-format.ts",
    url: new URL(
      "../../../scene-contract/src/output-format.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/passage-audio.ts",
    url: new URL(
      "../../../scene-contract/src/passage-audio.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/passage-validation.ts",
    url: new URL(
      "../../../scene-contract/src/passage-validation.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/prepared.ts",
    url: new URL("../../../scene-contract/src/prepared.ts", import.meta.url),
  },
  {
    name: "scene-contract/src/sfx-generation.ts",
    url: new URL(
      "../../../scene-contract/src/sfx-generation.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/shared-effects.ts",
    url: new URL(
      "../../../scene-contract/src/shared-effects.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/soundtrack-project.ts",
    url: new URL(
      "../../../scene-contract/src/soundtrack-project.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/story-acting.ts",
    url: new URL(
      "../../../scene-contract/src/story-acting.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/story-authoring.ts",
    url: new URL(
      "../../../scene-contract/src/story-authoring.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/story-motion-validation.ts",
    url: new URL(
      "../../../scene-contract/src/story-motion-validation.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/story-motion.ts",
    url: new URL(
      "../../../scene-contract/src/story-motion.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/story-passage.ts",
    url: new URL(
      "../../../scene-contract/src/story-passage.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/story-validation.ts",
    url: new URL(
      "../../../scene-contract/src/story-validation.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/story.ts",
    url: new URL("../../../scene-contract/src/story.ts", import.meta.url),
  },
  {
    name: "scene-contract/src/typography-events.ts",
    url: new URL(
      "../../../scene-contract/src/typography-events.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/typography-style.ts",
    url: new URL(
      "../../../scene-contract/src/typography-style.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/typography-validation.ts",
    url: new URL(
      "../../../scene-contract/src/typography-validation.ts",
      import.meta.url,
    ),
  },
  {
    name: "scene-contract/src/typography.ts",
    url: new URL("../../../scene-contract/src/typography.ts", import.meta.url),
  },
]);
/** Actual pinned non-Three ESM runtime closure. Resolved and hashed by the Node IO owner. */
export const native3DAppearanceExternalModules: readonly {
  readonly name: string;
  readonly packageName: string;
  readonly packageRelativePath: string;
  readonly expectedVersion: string;
}[] = Object.freeze([
  {
    name: "external/clipper2-ts/dist/Clipper.js",
    packageName: "clipper2-ts",
    packageRelativePath: "dist/Clipper.js",
    expectedVersion: "2.0.1-18",
  },
  {
    name: "external/clipper2-ts/dist/Core.js",
    packageName: "clipper2-ts",
    packageRelativePath: "dist/Core.js",
    expectedVersion: "2.0.1-18",
  },
  {
    name: "external/clipper2-ts/dist/Engine.js",
    packageName: "clipper2-ts",
    packageRelativePath: "dist/Engine.js",
    expectedVersion: "2.0.1-18",
  },
  {
    name: "external/clipper2-ts/dist/Minkowski.js",
    packageName: "clipper2-ts",
    packageRelativePath: "dist/Minkowski.js",
    expectedVersion: "2.0.1-18",
  },
  {
    name: "external/clipper2-ts/dist/Offset.js",
    packageName: "clipper2-ts",
    packageRelativePath: "dist/Offset.js",
    expectedVersion: "2.0.1-18",
  },
  {
    name: "external/clipper2-ts/dist/RectClip.js",
    packageName: "clipper2-ts",
    packageRelativePath: "dist/RectClip.js",
    expectedVersion: "2.0.1-18",
  },
  {
    name: "external/clipper2-ts/dist/Shewchuk.js",
    packageName: "clipper2-ts",
    packageRelativePath: "dist/Shewchuk.js",
    expectedVersion: "2.0.1-18",
  },
  {
    name: "external/clipper2-ts/dist/Triangulation.js",
    packageName: "clipper2-ts",
    packageRelativePath: "dist/Triangulation.js",
    expectedVersion: "2.0.1-18",
  },
  {
    name: "external/clipper2-ts/dist/index.js",
    packageName: "clipper2-ts",
    packageRelativePath: "dist/index.js",
    expectedVersion: "2.0.1-18",
  },
  {
    name: "external/clipper2-ts/package.json",
    packageName: "clipper2-ts",
    packageRelativePath: "package.json",
    expectedVersion: "2.0.1-18",
  },
  {
    name: "external/earcut/package.json",
    packageName: "earcut",
    packageRelativePath: "package.json",
    expectedVersion: "3.0.2",
  },
  {
    name: "external/earcut/src/earcut.js",
    packageName: "earcut",
    packageRelativePath: "src/earcut.js",
    expectedVersion: "3.0.2",
  },
  {
    name: "external/zod/index.js",
    packageName: "zod",
    packageRelativePath: "index.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/package.json",
    packageName: "zod",
    packageRelativePath: "package.json",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/classic/checks.js",
    packageName: "zod",
    packageRelativePath: "v4/classic/checks.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/classic/coerce.js",
    packageName: "zod",
    packageRelativePath: "v4/classic/coerce.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/classic/compat.js",
    packageName: "zod",
    packageRelativePath: "v4/classic/compat.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/classic/errors.js",
    packageName: "zod",
    packageRelativePath: "v4/classic/errors.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/classic/external.js",
    packageName: "zod",
    packageRelativePath: "v4/classic/external.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/classic/iso.js",
    packageName: "zod",
    packageRelativePath: "v4/classic/iso.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/classic/parse.js",
    packageName: "zod",
    packageRelativePath: "v4/classic/parse.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/classic/schemas.js",
    packageName: "zod",
    packageRelativePath: "v4/classic/schemas.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/core/api.js",
    packageName: "zod",
    packageRelativePath: "v4/core/api.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/core/checks.js",
    packageName: "zod",
    packageRelativePath: "v4/core/checks.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/core/core.js",
    packageName: "zod",
    packageRelativePath: "v4/core/core.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/core/doc.js",
    packageName: "zod",
    packageRelativePath: "v4/core/doc.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/core/errors.js",
    packageName: "zod",
    packageRelativePath: "v4/core/errors.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/core/index.js",
    packageName: "zod",
    packageRelativePath: "v4/core/index.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/core/json-schema.js",
    packageName: "zod",
    packageRelativePath: "v4/core/json-schema.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/core/parse.js",
    packageName: "zod",
    packageRelativePath: "v4/core/parse.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/core/regexes.js",
    packageName: "zod",
    packageRelativePath: "v4/core/regexes.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/core/registries.js",
    packageName: "zod",
    packageRelativePath: "v4/core/registries.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/core/schemas.js",
    packageName: "zod",
    packageRelativePath: "v4/core/schemas.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/core/to-json-schema.js",
    packageName: "zod",
    packageRelativePath: "v4/core/to-json-schema.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/core/util.js",
    packageName: "zod",
    packageRelativePath: "v4/core/util.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/core/versions.js",
    packageName: "zod",
    packageRelativePath: "v4/core/versions.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/ar.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/ar.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/az.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/az.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/be.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/be.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/ca.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/ca.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/cs.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/cs.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/da.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/da.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/de.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/de.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/en.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/en.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/eo.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/eo.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/es.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/es.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/fa.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/fa.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/fi.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/fi.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/fr-CA.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/fr-CA.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/fr.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/fr.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/he.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/he.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/hu.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/hu.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/id.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/id.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/index.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/index.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/is.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/is.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/it.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/it.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/ja.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/ja.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/kh.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/kh.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/ko.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/ko.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/mk.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/mk.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/ms.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/ms.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/nl.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/nl.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/no.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/no.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/ota.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/ota.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/pl.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/pl.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/ps.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/ps.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/pt.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/pt.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/ru.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/ru.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/sl.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/sl.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/sv.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/sv.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/ta.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/ta.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/th.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/th.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/tr.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/tr.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/ua.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/ua.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/ur.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/ur.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/vi.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/vi.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/yo.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/yo.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/zh-CN.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/zh-CN.js",
    expectedVersion: "4.1.5",
  },
  {
    name: "external/zod/v4/locales/zh-TW.js",
    packageName: "zod",
    packageRelativePath: "v4/locales/zh-TW.js",
    expectedVersion: "4.1.5",
  },
]);
