import { readFile, mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { format } from "prettier";
import { z } from "zod";
import {
  CompositionSchema,
  CompositionLayerSchema,
  CompositionFpsSchema,
  COMPOSITION_SCHEMA_VERSION,
  COMPOSITION_LIMITS,
  COMPOSITION_DIAGNOSTICS,
  COMPOSITION_EFFECTS,
  COMPOSITION_BLEND_MODES,
  LEGACY_PROPERTY_ALIASES,
  LEGACY_UNAVAILABLE_PROPERTIES,
  EXPRESSION_BUILTINS,
  EXPRESSION_GRAMMAR,
  EXPRESSION_IDENTIFIERS,
  EXPRESSION_COMPONENTS,
  EXPRESSION_LIMITS,
  STORY_MOTION_PRESETS,
  TEXT_INTENT_PRESETS,
} from "@still-shift/scene-contract";
import { presets } from "@still-shift/motion";
type Schema = {
  $ref?: string;
  $defs?: Record<string, Schema>;
  type?: string | string[];
  const?: unknown;
  enum?: unknown[];
  properties?: Record<string, Schema>;
  required?: string[];
  anyOf?: Schema[];
  oneOf?: Schema[];
  prefixItems?: Schema[];
  items?: Schema;
  minimum?: number;
  maximum?: number;
  minItems?: number;
  maxItems?: number;
  minLength?: number;
  maxLength?: number;
  pattern?: string;
};
const code = (value: unknown) => `\`${String(value).replaceAll("|", "\\|")}\``;
const table = (headers: string[], rows: unknown[][]) =>
  `| ${headers.join(" | ")} |\n| ${headers.map(() => "---").join(" | ")} |\n${rows.map((row) => `| ${row.map((cell) => String(cell).replaceAll("\n", " ")).join(" | ")} |`).join("\n")}\n`;
function typeOf(node: Schema, root: Schema, depth = 0): string {
  if (depth > 5) return "object";
  if (node.$ref)
    return typeOf(
      root.$defs?.[node.$ref.split("/").at(-1)!] ?? {},
      root,
      depth + 1,
    );
  if (node.const !== undefined) return code(node.const);
  if (node.enum) return node.enum.map(code).join(", ");
  if (node.anyOf || node.oneOf)
    return [
      ...new Set(
        (node.anyOf ?? node.oneOf)!.map((item) =>
          typeOf(item, root, depth + 1),
        ),
      ),
    ].join(" or ");
  if (node.prefixItems)
    return `[${node.prefixItems.map((item) => typeOf(item, root, depth + 1)).join(", ")}]`;
  return Array.isArray(node.type)
    ? node.type.join(" or ")
    : (node.type ?? "JSON");
}
function fields(schema: z.ZodType): string {
  const root = z.toJSONSchema(schema, { reused: "ref" }) as Schema;
  return table(
    ["Field", "Required", "JSON form"],
    Object.entries(root.properties ?? {}).map(([name, node]) => [
      code(name),
      root.required?.includes(name) ? "yes" : "no",
      typeOf(node, root),
    ]),
  );
}
const example = `import { comp, solid, seq, presets } from "@still-shift/motion";

export default comp({ width: 640, height: 360, fps: 24, frames: 96 }, c => {
  const bar = c.add(solid("bar", { size: [48, 160], color: "#D96A3B" })
    .at(296, 260).anchor("bottom"));
  c.marker("land", 24, { label: "Bar arrives" });
  c.timeline(seq(bar.scaleY.from(0).to(1, 24), presets.settle(bar, 20, { amount: 8 })));
});`;
const commands = `pnpm still-shift comp validate --input program.ts
pnpm still-shift comp preview --input program.ts --watch
pnpm still-shift comp lint --input program.ts
pnpm still-shift comp export-json --input program.ts --output composition.json
pnpm still-shift comp bake --input program.ts --output baked.json
pnpm still-shift comp render --input program.ts --output clip.mp4`;
function skill(): string {
  return `---
name: compose-with-still-shift
description: Author and verify Still Shift TypeScript composition programs with timed layers, pinned assets and native motion. Use for code-authored motion clips and composition JSON in a Still Shift repository.
---

# Compose with Still Shift

Generated by \`pnpm schema:generate\`; edit \`scripts/generate-composition-reference.ts\` and the contract/registries to update it.

Work from the repository root with Node 22.23.1 and pnpm 10.29.3. Write a \`.ts\` program whose default export is a \`composition-1\` object, using \`@still-shift/motion\`. Top-level await and an awaited default export work. The \`comp\` callback is synchronous: resolve Node assets before entering it.

\`\`\`ts
${example}
\`\`\`

Use exactly one of \`frames\` or \`seconds\` for the composition duration. Allowed fps: ${CompositionFpsSchema.options.map((item) => item.value).join(", ")}. Composition frame counts are positive integers; animation durations are nonnegative integers, and \`{ seconds: n }\` durations use \`Math.round(n * fps)\`. Markers use composition frames. Author keys before the composition's last boundary.

- Delivered layers: solid, image, text, group, null, precomp, adjustment and registered providers. Native shapes/operators, 3D cameras/lights and video/audio layers are reserved for later milestones; schema presence does not imply a renderer is available. Rectangles use \`shape.rect\` or \`solid\` now.
- Layers added first are in front; later-added layers paint behind them. Put full-frame backdrop layers last, or use the composition background. For a delayed fade-in, start the layer at \`.opacity(0)\` (or gate visibility with \`inPoint\`); \`.from(0)\` sets the placed animation segment, rather than hiding an already-visible layer before that segment.
- Set transforms with \`.at(x,y)\`, \`.anchor("center" | "bottom" | ...)\`, \`.scale(x,y)\`, \`.rotate(degrees)\`, \`.opacity(value)\`, \`.parent(layer)\`, and native fields with \`.with(options)\`. Text without an explicit ID gets deterministic \`text\`, \`text-2\`, ... IDs.
- Add the actual layer object to \`c\` before animating it. Animate \`.x\`, \`.y\`, \`.position\`, \`.scaleX\`, \`.scaleY\`, \`.rotation\`, \`.alpha\` or \`.property(path)\` via \`.from(value).to(value,duration,easing)\`, \`.by(delta,duration,easing)\` and \`.keys([{frame,value,...}])\`. \`.opacity\` is the static setter; \`.alpha\` is the animation property.
- Use \`seq\`, \`par\`, \`stagger(motions,offset)\`, \`delay(duration,motion)\`, \`at("cue:id",motion)\` and \`after(referenceClip,offset,motion)\`. A clip can be placed only once. Same-property key overlaps and conflicting boundary values fail; whole-vector and component tracks cannot be mixed.
- Timed layer fields are \`inPoint\`, \`outPoint\`, \`startFrame\` and \`stretch\`, set via \`.with({ inPoint: 12, outPoint: 96 })\`. In/out points gate visibility in composition frames, with an exclusive out point. Keys use local time \`(scopeFrame - startFrame) / stretch\`; timeline placement writes authored key times. For ordinary root cue-based timelines, keep the default \`startFrame: 0\` and use in/out points for visibility. Setting a layer's startFrame to the cue and also placing its animation with at(cue) offsets the animation twice.
- Motion recipes: ${Object.keys(presets)
    .filter((name) => name !== "text")
    .map(code)
    .join(
      ", ",
    )}; call \`presets.settle(layer,duration,{amount:8,property:"y"})\` inside a timeline. These emit staged additive drivers/carriers. \`drawOn\` currently requires a \`story.path@1.0.0\` provider. Text recipes: ${Object.keys(presets.text).map(code).join(", ")}; \`presets.text.emphasize(title,12,{manner:"highlight"})\`. Correction requires \`replacement\`; qualification requires a smaller text layer and a \`target\` claim. Retype/count require two states; count also requires numeric states and a style with tabular figures. Presets need a positive duration ending within the composition.
- Pin images/fonts using \`imageAsset\` and \`fontAsset\` from \`@still-shift/motion/node\`, for example \`await imageAsset("art","./art.svg",{relativeTo:import.meta.url})\`. These read real bytes, dimensions and SHA-256. \`image("hero",asset)\` registers its image automatically; pass fonts in \`comp({assets:[font],...})\` and \`text("Title",{fontAsset:font.id,...})\`. For a repository-local font use \`assets/story-motion/fonts/plex-sans-semibold.ttf\` with weight \`"600"\`. Browser callers supply precomputed asset descriptors. Authored system fonts are errors; do not fabricate hashes.
- Reused precomps are separate instances. Target instance paths such as \`instance("left","child").path("x")\`; nested definitions cannot silently carry root-only drivers/camera/expressions. Parent and matte references name layers in the same scope.
- Runtime expressions use the constrained text syntax via the expr tagged template, or \`ref("left/child.x")\`. Builder TypeScript runs once; arbitrary JavaScript does not run per frame. Read the linked generated reference for property paths, expression grammar, built-ins, masks/effects and diagnostics when needed.

\`\`\`sh
${commands}
\`\`\`

Validate after authoring and fix located diagnostics before rendering. CLI accepts \`.json\`, \`.ts\`, \`.mts\` and \`.cts\`; JSON export rebases pinned asset paths to its output folder. Output writes refuse to overwrite existing files. Watch preview retains the last valid pixels/frame on an invalid rebuild. Lint reports motion craft separately from schema validity; use its findings to improve the clip. Verification runs locally using pnpm.

Read [the generated composition reference](../../docs/composition-reference.md) for contract details and advanced operations. See [eight small programs](../../examples/composition/) and [the 197-line Unequal Margins program](../../examples/composition/unequal-margins/program.ts) for concrete authoring patterns.
`;
}
async function reference(root: string): Promise<string> {
  const notes = await readFile(
    resolve(root, "docs/composition-reference-notes.md"),
    "utf8",
  );
  const layers = CompositionLayerSchema.options
    .map((schema) => {
      const json = z.toJSONSchema(schema, { reused: "ref" }) as Schema;
      return `### ${code(json.properties!.type!.const)} contract\n\n${fields(schema)}`;
    })
    .join("\n");
  const builtins = Object.entries(EXPRESSION_BUILTINS).map(
    ([name, definition]) => [
      code(name),
      definition.overloads
        .map(
          (overload) =>
            `(${overload.params.map((param) => (typeof param === "string" ? param : `literal ${param.literal.join("–")}`)).join(", ")}) → ${typeof overload.result === "string" ? overload.result : "dependent result"}`,
        )
        .join("; "),
      definition.summary,
    ],
  );
  const effects = Object.entries(COMPOSITION_EFFECTS).flatMap(
    ([name, definition]) =>
      Object.entries(definition.properties).map(([property, descriptor]) => [
        code(name),
        code(property),
        descriptor.type,
        code(descriptor.default),
        descriptor.type === "scalar"
          ? `${descriptor.min}–${descriptor.max}${descriptor.integer ? " (integer)" : ""}`
          : "colour",
      ]),
  );
  return `# \`${COMPOSITION_SCHEMA_VERSION}\` reference

This file is generated by \`pnpm schema:generate\` and checked by \`pnpm schema:check\`. Contract indexes come from Zod schemas and native registries. The maintained implementation notes live in [composition-reference-notes.md](./composition-reference-notes.md); update that source for explanatory prose. Do not edit this generated output directly.

## TypeScript authoring

Use [compose-with-still-shift](../skills/compose-with-still-shift/SKILL.md) for the complete compact workflow. Ordinary builder programs emit native JSON and retain source locations.

\`\`\`ts
${example}
\`\`\`

\`\`\`sh
${commands}
\`\`\`

## Generated root contract

${fields(CompositionSchema)}

See [the generated JSON Schema](../packages/scene-contract/schemas/composition-1.schema.json) for full nested bounds and structural unions. Run semantic validation for references, paths and cycles. The layer schemas reserve some future features; the implementation notes' availability section records delivered behavior.

## Generated layer contracts

${layers}

## Generated property aliases

Paths use layer instance IDs: \`left/hero.transform.position.x\`. A source precomp definition ID cannot replace its host's instance route. Masks/effects use authored IDs in selectors, such as \`hero.masks[window].feather\` and \`hero.effects[glow].radius\`; builder lowering emits the matching array indices. Transform vectors have x/y components; colours have r/g/b/a. Whole-colour builder keys are supported; component keys require expressions or drivers. See [property paths](#property-paths) for canonical availability and read-only paths.

${table(
  ["Alias", "Canonical property"],
  Object.entries(LEGACY_PROPERTY_ALIASES).map(([a, b]) => [code(a), code(b)]),
)}

Reserved aliases:

${table(
  ["Property", "Required milestone"],
  Object.entries(LEGACY_UNAVAILABLE_PROPERTIES).map(([a, b]) => [code(a), b]),
)}

## Generated expression grammar

\`\`\`text
${EXPRESSION_GRAMMAR}
\`\`\`

Identifiers: ${EXPRESSION_IDENTIFIERS.map(code).join(", ")}. Components: ${EXPRESSION_COMPONENTS.map(code).join(", ")}. Expressions are finite scalars, 2D/3D vectors, RGBA colours or booleans. Strings are restricted to builtin arguments for paths, signals and loop modes. Only registered calls and component access are allowed. Limits: ${EXPRESSION_LIMITS.maxLength} source characters, ${EXPRESSION_LIMITS.maxNodes} AST nodes, ${EXPRESSION_LIMITS.maxNesting} nesting levels.

## Generated built-ins

\`T\` is a numeric scalar/vector/colour; \`Tb\` is a compatible numeric input with scalar broadcasting. A path result has its referenced property's type. Builtin argument literal bounds are part of the checker registry.

${table(["Function", "Overloads", "Behavior"], builtins)}

## Generated effect registry

${table(["Effect", "Property", "Type", "Default", "Range"], effects)}

Blend modes: ${COMPOSITION_BLEND_MODES.map(code).join(", ")}.

## Generated intent registry

Motion intents: ${Object.keys(STORY_MOTION_PRESETS)
    .filter((name) => name !== "version")
    .map(code)
    .join(", ")}.

${table(
  ["Text intent", "Purpose"],
  TEXT_INTENT_PRESETS.map((item) => [code(item.preset), item.label]),
)}

## Generated limits

${table(
  ["Limit", "Value"],
  Object.entries(COMPOSITION_LIMITS).map(([name, value]) => [
    code(name),
    value,
  ]),
)}

## Generated diagnostics

Schema validation yields stable codes with JSON paths; builder input also yields authored file:line:column sites. Warnings can be promoted for authored input, including unpinned system fonts.

${table(
  ["Code", "Meaning"],
  Object.entries(COMPOSITION_DIAGNOSTICS).map(([name, summary]) => [
    code(name),
    summary,
  ]),
)}

---

${notes.replace(/^#.*\n/, "")}
`;
}
export async function generateCompositionReference(
  root: string,
  check = false,
): Promise<void> {
  const targets = [
    { path: "docs/composition-reference.md", text: await reference(root) },
    { path: "skills/compose-with-still-shift/SKILL.md", text: skill() },
  ];
  const stale = [];
  for (const target of targets) {
    const text = await format(target.text, { parser: "markdown" }),
      path = resolve(root, target.path);
    if (check) {
      if ((await readFile(path, "utf8").catch(() => "")) !== text)
        stale.push(target.path);
    } else {
      await mkdir(resolve(path, ".."), { recursive: true });
      await writeFile(path, text);
      console.log(`Generated ${target.path}`);
    }
  }
  if (stale.length)
    throw new Error(
      `Composition reference is stale: ${stale.join(", ")}. Run pnpm schema:generate.`,
    );
}
if (
  process.argv[1] &&
  pathToFileURL(resolve(process.argv[1])).href === import.meta.url
)
  await generateCompositionReference(
    resolve(import.meta.dirname, ".."),
    process.argv.includes("--check"),
  );
