import { afterEach, expect, it, vi } from "vitest";
import {
  radialDistortionControls,
  radialSourcePoint,
  type RadialControls,
} from "../../packages/renderer-core/src/composition/render/radial-distortion.ts";
import { ManagedMemory } from "../../packages/renderer-core/src/managed-memory.ts";
import { withManagedMemory } from "../../packages/renderer-core/src/managed-memory-context.ts";
import {
  allocateRenderMetadata,
  releaseRenderMetadata,
} from "../../packages/renderer-core/src/managed-metadata.ts";
const originals = [
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [32, 16],
      amount: 0,
    },
    dimensions: [2, 2],
    destination: [-1, -1],
    value: [-1, -1],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "factors",
      "factors.1280",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [32, 16],
      amount: 0,
    },
    dimensions: [2, 2],
    destination: [0.5, 0.5],
    value: [0.5, 0.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "factors",
      "factors.80",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [32, 16],
      amount: 0,
    },
    dimensions: [2, 2],
    destination: [1.5, 1.5],
    value: [1.5, 1.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "factors",
      "factors.80",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [32, 16],
      amount: 0,
    },
    dimensions: [2, 2],
    destination: [1, 1],
    value: [1, 1],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "factors",
      "factors.0",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [32, 16],
      amount: 0,
    },
    dimensions: [2, 2],
    destination: [1.5, 1.5],
    value: [1.5, 1.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "factors",
      "factors.80",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [32, 16],
      amount: 0,
    },
    dimensions: [128, 64],
    destination: [-1, -1],
    value: [-1, -1],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [32, 16],
      amount: 0,
    },
    dimensions: [128, 64],
    destination: [0.5, 0.5],
    value: [0.5, 0.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [32, 16],
      amount: 0,
    },
    dimensions: [128, 64],
    destination: [1.5, 1.5],
    value: [1.5, 1.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [32, 16],
      amount: 0,
    },
    dimensions: [128, 64],
    destination: [64, 32],
    value: [64, 32],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "factors",
      "factors.0",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [32, 16],
      amount: 0,
    },
    dimensions: [128, 64],
    destination: [127.5, 63.5],
    value: [127.5, 63.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [32, 16],
      amount: 0,
    },
    dimensions: [8192, 8192],
    destination: [-1, -1],
    value: [-1, -1],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [32, 16],
      amount: 0,
    },
    dimensions: [8192, 8192],
    destination: [0.5, 0.5],
    value: [0.5, 0.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [32, 16],
      amount: 0,
    },
    dimensions: [8192, 8192],
    destination: [1.5, 1.5],
    value: [1.5, 1.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [32, 16],
      amount: 0,
    },
    dimensions: [8192, 8192],
    destination: [4096, 4096],
    value: [4096, 4096],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "factors",
      "factors.0",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [32, 16],
      amount: 0,
    },
    dimensions: [8192, 8192],
    destination: [8191.5, 8191.5],
    value: [8191.5, 8191.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.3, 0.7],
      radius: [2.5, 1.25],
      amount: 1,
    },
    dimensions: [2, 2],
    destination: [-1, -1],
    value: [-1, -1],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.3, 0.7],
      radius: [2.5, 1.25],
      amount: 1,
    },
    dimensions: [2, 2],
    destination: [0.5, 0.5],
    value: [0.5, 0.6875],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "factors",
      "factors.32185",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.3, 0.7],
      radius: [2.5, 1.25],
      amount: 1,
    },
    dimensions: [2, 2],
    destination: [1.5, 1.5],
    value: [0.8125, 1.375],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "factors",
      "factors.8546",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.3, 0.7],
      radius: [2.5, 1.25],
      amount: 1,
    },
    dimensions: [2, 2],
    destination: [1, 1],
    value: [0.6875, 1.25],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "factors",
      "factors.7220",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.3, 0.7],
      radius: [2.5, 1.25],
      amount: 1,
    },
    dimensions: [2, 2],
    destination: [1.5, 1.5],
    value: [0.8125, 1.375],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "factors",
      "factors.8546",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.3, 0.7],
      radius: [2.5, 1.25],
      amount: 1,
    },
    dimensions: [128, 64],
    destination: [-1, -1],
    value: [-1, -1],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.3, 0.7],
      radius: [2.5, 1.25],
      amount: 1,
    },
    dimensions: [128, 64],
    destination: [0.5, 0.5],
    value: [0.5, 0.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.3, 0.7],
      radius: [2.5, 1.25],
      amount: 1,
    },
    dimensions: [128, 64],
    destination: [1.5, 1.5],
    value: [1.5, 1.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.3, 0.7],
      radius: [2.5, 1.25],
      amount: 1,
    },
    dimensions: [128, 64],
    destination: [64, 32],
    value: [64, 32],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.3, 0.7],
      radius: [2.5, 1.25],
      amount: 1,
    },
    dimensions: [128, 64],
    destination: [127.5, 63.5],
    value: [127.5, 63.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.3, 0.7],
      radius: [2.5, 1.25],
      amount: 1,
    },
    dimensions: [8192, 8192],
    destination: [-1, -1],
    value: [-1, -1],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.3, 0.7],
      radius: [2.5, 1.25],
      amount: 1,
    },
    dimensions: [8192, 8192],
    destination: [0.5, 0.5],
    value: [0.5, 0.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.3, 0.7],
      radius: [2.5, 1.25],
      amount: 1,
    },
    dimensions: [8192, 8192],
    destination: [1.5, 1.5],
    value: [1.5, 1.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.3, 0.7],
      radius: [2.5, 1.25],
      amount: 1,
    },
    dimensions: [8192, 8192],
    destination: [4096, 4096],
    value: [4096, 4096],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.3, 0.7],
      radius: [2.5, 1.25],
      amount: 1,
    },
    dimensions: [8192, 8192],
    destination: [8191.5, 8191.5],
    value: [8191.5, 8191.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [0.0625, 8192],
      amount: -1,
    },
    dimensions: [2, 2],
    destination: [-1, -1],
    value: [-1, -1],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [0.0625, 8192],
      amount: -1,
    },
    dimensions: [2, 2],
    destination: [0.5, 0.5],
    value: [0.5, 0.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [0.0625, 8192],
      amount: -1,
    },
    dimensions: [2, 2],
    destination: [1.5, 1.5],
    value: [1.5, 1.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [0.0625, 8192],
      amount: -1,
    },
    dimensions: [2, 2],
    destination: [1, 1],
    value: [1, 1],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "factors",
      "factors.0",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [0.0625, 8192],
      amount: -1,
    },
    dimensions: [2, 2],
    destination: [1.5, 1.5],
    value: [1.5, 1.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [0.0625, 8192],
      amount: -1,
    },
    dimensions: [128, 64],
    destination: [-1, -1],
    value: [-1, -1],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [0.0625, 8192],
      amount: -1,
    },
    dimensions: [128, 64],
    destination: [0.5, 0.5],
    value: [0.5, 0.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [0.0625, 8192],
      amount: -1,
    },
    dimensions: [128, 64],
    destination: [1.5, 1.5],
    value: [1.5, 1.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [0.0625, 8192],
      amount: -1,
    },
    dimensions: [128, 64],
    destination: [64, 32],
    value: [64, 32],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "factors",
      "factors.0",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [0.0625, 8192],
      amount: -1,
    },
    dimensions: [128, 64],
    destination: [127.5, 63.5],
    value: [127.5, 63.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [0.0625, 8192],
      amount: -1,
    },
    dimensions: [8192, 8192],
    destination: [-1, -1],
    value: [-1, -1],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [0.0625, 8192],
      amount: -1,
    },
    dimensions: [8192, 8192],
    destination: [0.5, 0.5],
    value: [0.5, 0.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [0.0625, 8192],
      amount: -1,
    },
    dimensions: [8192, 8192],
    destination: [1.5, 1.5],
    value: [1.5, 1.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [0.0625, 8192],
      amount: -1,
    },
    dimensions: [8192, 8192],
    destination: [4096, 4096],
    value: [4096, 4096],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "factors",
      "factors.0",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.bulge",
    params: {
      center: [0.5, 0.5],
      radius: [0.0625, 8192],
      amount: -1,
    },
    dimensions: [8192, 8192],
    destination: [8191.5, 8191.5],
    value: [8191.5, 8191.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "radius",
      "radius.0",
      "radius",
      "radius.1",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 0,
      wavelength: 32,
      phase: 0,
      decay: 0,
    },
    dimensions: [2, 2],
    destination: [-1, -1],
    value: [-1, -1],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.45",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 0,
      wavelength: 32,
      phase: 0,
      decay: 0,
    },
    dimensions: [2, 2],
    destination: [0.5, 0.5],
    value: [0.5, 0.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.11",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 0,
      wavelength: 32,
      phase: 0,
      decay: 0,
    },
    dimensions: [2, 2],
    destination: [1.5, 1.5],
    value: [1.5, 1.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.11",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 0,
      wavelength: 32,
      phase: 0,
      decay: 0,
    },
    dimensions: [2, 2],
    destination: [1, 1],
    value: [1, 1],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.0",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 0,
      wavelength: 32,
      phase: 0,
      decay: 0,
    },
    dimensions: [2, 2],
    destination: [1.5, 1.5],
    value: [1.5, 1.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.11",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 0,
      wavelength: 32,
      phase: 0,
      decay: 0,
    },
    dimensions: [128, 64],
    destination: [-1, -1],
    value: [-1, -1],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.1166",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 0,
      wavelength: 32,
      phase: 0,
      decay: 0,
    },
    dimensions: [128, 64],
    destination: [0.5, 0.5],
    value: [0.5, 0.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.1134",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 0,
      wavelength: 32,
      phase: 0,
      decay: 0,
    },
    dimensions: [128, 64],
    destination: [1.5, 1.5],
    value: [1.5, 1.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.1112",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 0,
      wavelength: 32,
      phase: 0,
      decay: 0,
    },
    dimensions: [128, 64],
    destination: [64, 32],
    value: [64, 32],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.0",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 0,
      wavelength: 32,
      phase: 0,
      decay: 0,
    },
    dimensions: [128, 64],
    destination: [127.5, 63.5],
    value: [127.5, 63.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.1134",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 0,
      wavelength: 32,
      phase: 0,
      decay: 0,
    },
    dimensions: [8192, 8192],
    destination: [-1, -1],
    value: [-1, -1],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.92704",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 0,
      wavelength: 32,
      phase: 0,
      decay: 0,
    },
    dimensions: [8192, 8192],
    destination: [0.5, 0.5],
    value: [0.5, 0.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.92670",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 0,
      wavelength: 32,
      phase: 0,
      decay: 0,
    },
    dimensions: [8192, 8192],
    destination: [1.5, 1.5],
    value: [1.5, 1.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.92647",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 0,
      wavelength: 32,
      phase: 0,
      decay: 0,
    },
    dimensions: [8192, 8192],
    destination: [4096, 4096],
    value: [4096, 4096],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.0",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 0,
      wavelength: 32,
      phase: 0,
      decay: 0,
    },
    dimensions: [8192, 8192],
    destination: [8191.5, 8191.5],
    value: [8191.5, 8191.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.92670",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.3, 0.7],
      amplitude: 4,
      wavelength: 32,
      phase: 90,
      decay: 0.3,
    },
    dimensions: [2, 2],
    destination: [-1, -1],
    value: [-2.25, -2.875],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.46",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.3, 0.7],
      amplitude: 4,
      wavelength: 32,
      phase: 90,
      decay: 0.3,
    },
    dimensions: [2, 2],
    destination: [0.5, 0.5],
    value: [0, -3],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.14",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.3, 0.7],
      amplitude: 4,
      wavelength: 32,
      phase: 90,
      decay: 0.3,
    },
    dimensions: [2, 2],
    destination: [1.5, 1.5],
    value: [4.9375, 1.9375],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.14",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.3, 0.7],
      amplitude: 4,
      wavelength: 32,
      phase: 90,
      decay: 0.3,
    },
    dimensions: [2, 2],
    destination: [1, 1],
    value: [3.75, -1.8125],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.8",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.3, 0.7],
      amplitude: 4,
      wavelength: 32,
      phase: 90,
      decay: 0.3,
    },
    dimensions: [2, 2],
    destination: [1.5, 1.5],
    value: [4.9375, 1.9375],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.14",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.3, 0.7],
      amplitude: 4,
      wavelength: 32,
      phase: 90,
      decay: 0.3,
    },
    dimensions: [128, 64],
    destination: [-1, -1],
    value: [-2.75, -3],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.966",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.3, 0.7],
      amplitude: 4,
      wavelength: 32,
      phase: 90,
      decay: 0.3,
    },
    dimensions: [128, 64],
    destination: [0.5, 0.5],
    value: [-0.5, -0.6875],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.932",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.3, 0.7],
      amplitude: 4,
      wavelength: 32,
      phase: 90,
      decay: 0.3,
    },
    dimensions: [128, 64],
    destination: [1.5, 1.5],
    value: [1.0625, 1],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.910",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.3, 0.7],
      amplitude: 4,
      wavelength: 32,
      phase: 90,
      decay: 0.3,
    },
    dimensions: [128, 64],
    destination: [64, 32],
    value: [66.625, 30.625],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.458",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.3, 0.7],
      amplitude: 4,
      wavelength: 32,
      phase: 90,
      decay: 0.3,
    },
    dimensions: [128, 64],
    destination: [127.5, 63.5],
    value: [129.25, 63.8125],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.1457",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.3, 0.7],
      amplitude: 4,
      wavelength: 32,
      phase: 90,
      decay: 0.3,
    },
    dimensions: [8192, 8192],
    destination: [-1, -1],
    value: [-2.25, -3.8125],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.99842",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.3, 0.7],
      amplitude: 4,
      wavelength: 32,
      phase: 90,
      decay: 0.3,
    },
    dimensions: [8192, 8192],
    destination: [0.5, 0.5],
    value: [-0.75, -2.3125],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.99810",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.3, 0.7],
      amplitude: 4,
      wavelength: 32,
      phase: 90,
      decay: 0.3,
    },
    dimensions: [8192, 8192],
    destination: [1.5, 1.5],
    value: [0.25, -1.3125],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.99789",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.3, 0.7],
      amplitude: 4,
      wavelength: 32,
      phase: 90,
      decay: 0.3,
    },
    dimensions: [8192, 8192],
    destination: [4096, 4096],
    value: [4094, 4097.9375],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.37072",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.3, 0.7],
      amplitude: 4,
      wavelength: 32,
      phase: 90,
      decay: 0.3,
    },
    dimensions: [8192, 8192],
    destination: [8191.5, 8191.5],
    value: [8194.25, 8192.6875],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.99810",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0, 1],
      amplitude: -1000,
      wavelength: 0.0625,
      phase: -270,
      decay: 8,
    },
    dimensions: [2, 2],
    destination: [-1, -1],
    value: [null, null],
    kinds: ["NaN", "NaN"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.50",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0, 1],
      amplitude: -1000,
      wavelength: 0.0625,
      phase: -270,
      decay: 8,
    },
    dimensions: [2, 2],
    destination: [0.5, 0.5],
    value: [-0.125, 2.3125],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.25",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0, 1],
      amplitude: -1000,
      wavelength: 0.0625,
      phase: -270,
      decay: 8,
    },
    dimensions: [2, 2],
    destination: [1.5, 1.5],
    value: [-0.375, 2.0625],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.25",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0, 1],
      amplitude: -1000,
      wavelength: 0.0625,
      phase: -270,
      decay: 8,
    },
    dimensions: [2, 2],
    destination: [1, 1],
    value: [-2, 3.9375],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.22",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0, 1],
      amplitude: -1000,
      wavelength: 0.0625,
      phase: -270,
      decay: 8,
    },
    dimensions: [2, 2],
    destination: [1.5, 1.5],
    value: [-0.375, 2.0625],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.25",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0, 1],
      amplitude: -1000,
      wavelength: 0.0625,
      phase: -270,
      decay: 8,
    },
    dimensions: [128, 64],
    destination: [-1, -1],
    value: [-0.75, 16.1875],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.1040",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0, 1],
      amplitude: -1000,
      wavelength: 0.0625,
      phase: -270,
      decay: 8,
    },
    dimensions: [128, 64],
    destination: [0.5, 0.5],
    value: [0.3125, 19.375],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.1016",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0, 1],
      amplitude: -1000,
      wavelength: 0.0625,
      phase: -270,
      decay: 8,
    },
    dimensions: [128, 64],
    destination: [1.5, 1.5],
    value: [1, 21.5625],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.1000",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0, 1],
      amplitude: -1000,
      wavelength: 0.0625,
      phase: -270,
      decay: 8,
    },
    dimensions: [128, 64],
    destination: [64, 32],
    value: [53.6875, 37.125],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.1144",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0, 1],
      amplitude: -1000,
      wavelength: 0.0625,
      phase: -270,
      decay: 8,
    },
    dimensions: [128, 64],
    destination: [127.5, 63.5],
    value: [127.125, 63.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.2040",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0, 1],
      amplitude: -1000,
      wavelength: 0.0625,
      phase: -270,
      decay: 8,
    },
    dimensions: [8192, 8192],
    destination: [-1, -1],
    value: [-1, -1],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.131088",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0, 1],
      amplitude: -1000,
      wavelength: 0.0625,
      phase: -270,
      decay: 8,
    },
    dimensions: [8192, 8192],
    destination: [0.5, 0.5],
    value: [0.5, 0.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.131064",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0, 1],
      amplitude: -1000,
      wavelength: 0.0625,
      phase: -270,
      decay: 8,
    },
    dimensions: [8192, 8192],
    destination: [1.5, 1.5],
    value: [1.5, 1.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.131048",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0, 1],
      amplitude: -1000,
      wavelength: 0.0625,
      phase: -270,
      decay: 8,
    },
    dimensions: [8192, 8192],
    destination: [4096, 4096],
    value: [4094, 4098],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.92681",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0, 1],
      amplitude: -1000,
      wavelength: 0.0625,
      phase: -270,
      decay: 8,
    },
    dimensions: [8192, 8192],
    destination: [8191.5, 8191.5],
    value: [8191.5, 8191.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.131064",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 1000,
      wavelength: 8192,
      phase: 180,
      decay: 0,
    },
    dimensions: [2, 2],
    destination: [-1, -1],
    value: [0.5, 0.5],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.45",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 1000,
      wavelength: 8192,
      phase: 180,
      decay: 0,
    },
    dimensions: [2, 2],
    destination: [0.5, 0.5],
    value: [0.875, 0.875],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.11",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 1000,
      wavelength: 8192,
      phase: 180,
      decay: 0,
    },
    dimensions: [2, 2],
    destination: [1.5, 1.5],
    value: [1.0625, 1.0625],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.11",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 1000,
      wavelength: 8192,
      phase: 180,
      decay: 0,
    },
    dimensions: [2, 2],
    destination: [1, 1],
    value: [1, 1],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.0",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 1000,
      wavelength: 8192,
      phase: 180,
      decay: 0,
    },
    dimensions: [2, 2],
    destination: [1.5, 1.5],
    value: [1.0625, 1.0625],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.11",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 1000,
      wavelength: 8192,
      phase: 180,
      decay: 0,
    },
    dimensions: [128, 64],
    destination: [-1, -1],
    value: [48.8125, 24.25],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.1166",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 1000,
      wavelength: 8192,
      phase: 180,
      decay: 0,
    },
    dimensions: [128, 64],
    destination: [0.5, 0.5],
    value: [49.125, 24.625],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.1134",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 1000,
      wavelength: 8192,
      phase: 180,
      decay: 0,
    },
    dimensions: [128, 64],
    destination: [1.5, 1.5],
    value: [49.375, 24.875],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.1112",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 1000,
      wavelength: 8192,
      phase: 180,
      decay: 0,
    },
    dimensions: [128, 64],
    destination: [64, 32],
    value: [64, 32],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.0",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 1000,
      wavelength: 8192,
      phase: 180,
      decay: 0,
    },
    dimensions: [128, 64],
    destination: [127.5, 63.5],
    value: [78.8125, 39.3125],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.1134",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 1000,
      wavelength: 8192,
      phase: 180,
      decay: 0,
    },
    dimensions: [8192, 8192],
    destination: [-1, -1],
    value: [-683.1875, -683.1875],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.92704",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 1000,
      wavelength: 8192,
      phase: 180,
      decay: 0,
    },
    dimensions: [8192, 8192],
    destination: [0.5, 0.5],
    value: [-681.4375, -681.4375],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.92670",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 1000,
      wavelength: 8192,
      phase: 180,
      decay: 0,
    },
    dimensions: [8192, 8192],
    destination: [1.5, 1.5],
    value: [-680.3125, -680.3125],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.92647",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 1000,
      wavelength: 8192,
      phase: 180,
      decay: 0,
    },
    dimensions: [8192, 8192],
    destination: [4096, 4096],
    value: [4096, 4096],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.0",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
  {
    id: "distort.ripple",
    params: {
      center: [0.5, 0.5],
      amplitude: 1000,
      wavelength: 8192,
      phase: 180,
      decay: 0,
    },
    dimensions: [8192, 8192],
    destination: [8191.5, 8191.5],
    value: [8873.375, 8873.375],
    kinds: ["number", "number"],
    accesses: [
      "center",
      "center.0",
      "center",
      "center.1",
      "bulge",
      "factors",
      "factors.92670",
      "center",
      "center.0",
      "center",
      "center.1",
    ],
  },
] as const;
const limits = { pixels: 1024, metadata: 4096 };
function controls() {
  return radialDistortionControls(
    "distort.ripple",
    { center: [0.5, 0.5], amplitude: 4, wavelength: 32, phase: 0, decay: 0 },
    128,
    64,
  );
}
function empty(memory: ManagedMemory) {
  expect(memory.statistics.current).toEqual({ pixels: 0, metadata: 0 });
  expect(memory.statistics.reservations).toBe(0);
}
afterEach(() => vi.restoreAllMocks());
it("preserves all 105 original source points, original NaNs and exact borrowed getter order with actual result owners in active/inactive routes", async () => {
  for (const active of [false, true]) {
    const inputs = new Map<string, RadialControls>();
    for (const row of originals) {
      const key = JSON.stringify([row.id, row.params, row.dimensions]);
      if (!inputs.has(key))
        inputs.set(
          key,
          radialDistortionControls(
            row.id,
            row.params as never,
            row.dimensions[0]!,
            row.dimensions[1]!,
          ),
        );
    }
    const memory = new ManagedMemory(limits),
      run = async () => {
        for (const row of originals) {
          const c = inputs.get(
              JSON.stringify([row.id, row.params, row.dimensions]),
            )!,
            accesses: string[] = [];
          const view = (name: string, value: object) =>
            new Proxy(value, {
              get(t, k) {
                accesses.push(name + "." + String(k));
                return Reflect.get(t, k, t);
              },
            });
          const borrowed = new Proxy(
            {
              ...c,
              center: view("center", c.center),
              radius: view("radius", c.radius),
              factors: view("factors", c.factors),
            },
            {
              get(t, k, r) {
                accesses.push(String(k));
                return Reflect.get(t, k, r);
              },
            },
          );
          const point = radialSourcePoint(
            borrowed as never,
            row.destination[0]!,
            row.destination[1]!,
          );
          expect(point).toEqual(
            row.value.map((v, k) => (row.kinds[k] === "NaN" ? NaN : v)),
          );
          expect(accesses).toEqual(row.accesses);
          expect(memory.owns(point)).toBe(active);
          expect(memory.owns(c.factors.buffer)).toBe(false);
          expect(memory.statistics.current.metadata).toBe(active ? 272 : 0);
          releaseRenderMetadata(point);
          if (active) expect(point).toHaveLength(0);
          empty(memory);
        }
      };
    if (active) await withManagedMemory(memory, run);
    else await run();
    memory.dispose();
  }
});
it("rejects 271-byte result capacity before original point math or borrowed control getters", async () => {
  const c = controls(),
    memory = new ManagedMemory({ ...limits, metadata: 271 }),
    get = vi.fn((t: RadialControls, k: PropertyKey, r: unknown) =>
      Reflect.get(t, k, r),
    );
  const borrowed = new Proxy(c, { get });
  await withManagedMemory(memory, async () => {
    const round = vi.spyOn(Math, "round"),
      floor = vi.spyOn(Math, "floor");
    expect(() => radialSourcePoint(borrowed, 72, 32)).toThrow(/metadata/);
    expect(round).not.toHaveBeenCalled();
    expect(floor).not.toHaveBeenCalled();
    expect(get).not.toHaveBeenCalled();
    empty(memory);
  });
  memory.dispose();
});
it("holds actual result capacity through original math and retains the actual array outside render scope until consumer release", async () => {
  const c = controls(),
    memory = new ManagedMemory(limits);
  let point: readonly [number, number] | undefined;
  await withManagedMemory(memory, async () => {
    const round = Math.round,
      floor = Math.floor;
    let rounds = 0,
      floors = 0;
    vi.spyOn(Math, "round").mockImplementation((v) => {
      rounds++;
      expect(memory.statistics.current.metadata).toBe(272);
      return round(v);
    });
    vi.spyOn(Math, "floor").mockImplementation((v) => {
      floors++;
      expect(memory.statistics.current.metadata).toBe(272);
      return floor(v);
    });
    point = radialSourcePoint(c, 72, 32);
    expect(rounds).toBe(2);
    expect(floors).toBe(3);
    expect(memory.owns(point)).toBe(true);
  });
  expect(point).toEqual([76, 32]);
  expect(memory.statistics.current.metadata).toBe(272);
  releaseRenderMetadata(point!);
  expect(point).toHaveLength(0);
  empty(memory);
  expect(c.center).toEqual([1024, 512]);
  expect(c.factors.byteLength).toBeGreaterThan(0);
  memory.dispose();
});
it("preserves early/mid point math null over secondary lease cleanup and permits retry without mutating borrowed controls", async () => {
  for (const failAt of [1, 4]) {
    const c = controls(),
      before = [...c.factors],
      memory = new ManagedMemory(limits),
      reserve = memory.reserve.bind(memory);
    await withManagedMemory(memory, async () => {
      vi.spyOn(memory, "reserve").mockImplementation((...args) => {
        const lease = reserve(...args),
          release = lease.release.bind(lease);
        vi.spyOn(lease, "release").mockImplementation(() => {
          release();
          throw Error("secondary retirement");
        });
        return lease;
      });
      const round = Math.round,
        floor = Math.floor;
      let calls = 0;
      vi.spyOn(Math, "round").mockImplementation((v) => {
        if (++calls === failAt) throw null;
        return round(v);
      });
      vi.spyOn(Math, "floor").mockImplementation((v) => {
        if (++calls === failAt) throw null;
        return floor(v);
      });
      let failure: unknown = "unset";
      try {
        radialSourcePoint(c, 72, 32);
      } catch (error) {
        failure = error;
      }
      expect(failure).toBeNull();
      empty(memory);
      expect([...c.factors]).toEqual(before);
      vi.restoreAllMocks();
      const result = radialSourcePoint(c, 72, 32);
      expect(result).toEqual([76, 32]);
      releaseRenderMetadata(result);
      empty(memory);
    });
    memory.dispose();
  }
});
it("clears the actual completed point when metadata adoption throws null and permits retry", async () => {
  const c = controls(),
    memory = new ManagedMemory(limits);
  let actual: number[] | undefined;
  await withManagedMemory(memory, async () => {
    vi.spyOn(memory, "adopt").mockImplementation((v) => {
      actual = v as number[];
      throw null;
    });
    let failure: unknown = "unset";
    try {
      radialSourcePoint(c, 72, 32);
    } catch (error) {
      failure = error;
    }
    expect(failure).toBeNull();
    expect(actual).toHaveLength(0);
    empty(memory);
    vi.restoreAllMocks();
    const point = radialSourcePoint(c, 72, 32);
    expect(point).toEqual([76, 32]);
    releaseRenderMetadata(point);
    empty(memory);
  });
  memory.dispose();
});
it("retires actual returned points at scratch or allocator cleanup while borrowed factors and control vectors remain original", async () => {
  for (const scratch of [false, true]) {
    const c = controls(),
      before = [...c.factors],
      memory = new ManagedMemory(limits);
    let point: readonly [number, number] | undefined;
    if (scratch) memory.beginScratch();
    await withManagedMemory(memory, async () => {
      point = radialSourcePoint(c, 72, 32);
      expect(memory.owns(point)).toBe(true);
    });
    if (scratch) memory.endScratch();
    else memory.dispose();
    expect(point).toHaveLength(0);
    empty(memory);
    expect(c.center).toEqual([1024, 512]);
    expect(c.radius).toEqual([1, 1]);
    expect([...c.factors]).toEqual(before);
    releaseRenderMetadata(point!);
    memory.dispose();
  }
});
it("keeps an actual caller-admitted point route free of extra standalone reservations and clears its nested output at consumer cleanup", async () => {
  const c = controls(),
    memory = new ManagedMemory(limits);
  await withManagedMemory(memory, async () => {
    const control = allocateRenderMetadata<{ point?: number[] | undefined }>(
      512,
      () => ({}),
      false,
      (v) => {
        if (v.point) v.point.length = 0;
        v.point = undefined;
      },
    );
    const reserve = vi.spyOn(memory, "reserve");
    const point = radialSourcePoint(c, 72, 32, control);
    expect(point).toEqual([76, 32]);
    expect(control.point).toBe(point);
    expect(memory.owns(control)).toBe(true);
    expect(memory.statistics.current.metadata).toBe(512);
    expect(reserve).not.toHaveBeenCalled();
    expect(memory.owns(point)).toBe(false);
    releaseRenderMetadata(control);
    expect(point).toHaveLength(0);
    expect(control.point).toBeUndefined();
    empty(memory);
  });
  memory.dispose();
});
