import { vi } from "vitest";
export function fakeWebglDevice() {
  const gl = {
    MAX_TEXTURE_SIZE: 1,
    FRAMEBUFFER_COMPLETE: 2,
    TEXTURE_2D: 3,
    TEXTURE_MIN_FILTER: 4,
    TEXTURE_MAG_FILTER: 5,
    NEAREST: 6,
    LINEAR: 7,
    TEXTURE_WRAP_S: 8,
    TEXTURE_WRAP_T: 9,
    CLAMP_TO_EDGE: 10,
    RGBA32F: 11,
    RGBA8: 12,
    FRAMEBUFFER: 13,
    COLOR_ATTACHMENT0: 14,
    COLOR_BUFFER_BIT: 15,
    DITHER: 16,
    DEPTH_TEST: 17,
    STENCIL_TEST: 18,
    UNPACK_PREMULTIPLY_ALPHA_WEBGL: 19,
    UNPACK_COLORSPACE_CONVERSION_WEBGL: 20,
    NONE: 0,
    getParameter: vi.fn(() => 8192),
    getExtension: vi.fn(() => ({})),
    createVertexArray: vi.fn(() => ({})),
    bindVertexArray: vi.fn(),
    deleteVertexArray: vi.fn(),
    disable: vi.fn(),
    pixelStorei: vi.fn(),
    createTexture: vi.fn(() => ({})),
    createFramebuffer: vi.fn(() => ({})),
    bindTexture: vi.fn(),
    texParameteri: vi.fn(),
    texStorage2D: vi.fn(),
    bindFramebuffer: vi.fn(),
    framebufferTexture2D: vi.fn(),
    checkFramebufferStatus: vi.fn(() => 2),
    clearColor: vi.fn(),
    clear: vi.fn(),
    deleteTexture: vi.fn(),
    deleteFramebuffer: vi.fn(),
    deleteProgram: vi.fn(),
    viewport: vi.fn(),
    useProgram: vi.fn(),
    activeTexture: vi.fn(),
    uniform1i: vi.fn(),
    uniform1f: vi.fn(),
    uniform2fv: vi.fn(),
    uniform3fv: vi.fn(),
    uniform4fv: vi.fn(),
    uniformMatrix3fv: vi.fn(),
    drawArrays: vi.fn(),
    enable: vi.fn(),
    scissor: vi.fn(),
    TRIANGLES: 21,
    TEXTURE0: 22,
    SCISSOR_TEST: 23,
    READ_FRAMEBUFFER: 24,
    DRAW_FRAMEBUFFER: 27,
    isEnabled: vi.fn(() => false),
    blitFramebuffer: vi.fn(),
    RGBA: 25,
    UNSIGNED_BYTE: 26,
    NO_ERROR: 0,
    getError: vi.fn(() => 0),
    VERTEX_SHADER: 28,
    FRAGMENT_SHADER: 29,
    COMPILE_STATUS: 30,
    LINK_STATUS: 31,
    ACTIVE_UNIFORMS: 32,
    createShader: vi.fn((type: number) => ({ type })),
    shaderSource: vi.fn(),
    compileShader: vi.fn(),
    getShaderParameter: vi.fn(() => true),
    getShaderInfoLog: vi.fn(() => "original native compile failure"),
    deleteShader: vi.fn(),
    createProgram: vi.fn(() => ({})),
    attachShader: vi.fn(),
    linkProgram: vi.fn(),
    getProgramParameter: vi.fn(
      (_handle: unknown, name: number): boolean | number =>
        name === 31 ? true : 0,
    ),
    getProgramInfoLog: vi.fn(() => "original native link failure"),
    getActiveUniform: vi.fn((_handle: unknown, index: number) => ({
      name: index === 0 ? "source" : "gain",
      size: 1,
      type: 0,
    })),
    getUniformLocation: vi.fn((_handle: unknown, name: string) => ({ name })),
    readPixels: vi.fn((...args: unknown[]) => {
      const pixels = args[6] as Uint8Array;
      for (let i = 0; i < pixels.length; i++) pixels[i] = i % 256;
    }),
  };
  const getContext = vi.fn(() => gl);
  const canvas = {
    getContext,
    width: 32,
    height: 24,
  } as unknown as HTMLCanvasElement;
  return { gl, getContext, canvas };
}
